### ISSUE TITLE
[HOTFIX] Quebra da aplicação ao selecionar loja

### ISSUE THREAD

**Issue by byronkamal** [AgroMart/mobile-client#2]
A aplicação está quebrando ao selecionar loja. É necessário investigar melhor o erro e corrigi-lo.

**Vídeo com demonstração do erro:**

https://user-images.githubusercontent.com/18502121/132959451-bf145a4e-68aa-4f48-80aa-cb444f996800.mp4

**Comment by IgorVeludo2** [comment]
### Log do erro:

TypeError: null is not an object (evaluating 'endereco.bairro')

This error is located at:
    in StoreDetails (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)   
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)  
    in PanGestureHandler (at GestureHandlerNative.tsx:13)      
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)   
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)  
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:620)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:613)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:495)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)     
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at routes/index.tsx:21)
    in routes (at App.tsx:49)
    in AuthProvider (at hooks/index.tsx:10)
    in StoresProvider (at hooks/index.tsx:9)
    in CartProvider (at hooks/index.tsx:8)
    in AppProvider (at App.tsx:47)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.tsx:46)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by byronkamal** [comment]
Depois da investigação realizada, eu e o @IgorVeludo2 vimos que é obrigatório ter um endereço associado à loja no CMS. Após feita essa associação, o erro não ocorre mais.

**Associação loja com endereço**
<img width="1197" alt="Captura de Tela 2021-10-04 às 20 30 47" src="https://user-images.githubusercontent.com/18502121/135938127-78bedde4-dabf-4a43-a151-965b40acdfa0.png">
